# Basic
title: Dreaming.O
subtitle: 大智若愚，愚有大志
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 记录探索路上的点滴
creator: <a href="http://www.dreamingo.com">@dreamingo</a>

url: "http://www.dreamingo.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
# kramdown:
#     # parse_block_html: true

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: dreamingo
    # duoshuo: dreamingo
    
# Social
social:
    # zhihu: qu-zhan-ming
    weibo: 1957829952
    github: dreamingo
    mail: dreamingo.ozm@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
